lab:
  title: agentic-ni-demo2
  description: "3 routers in a full mesh topology with OSPF configuration."
  notes: ""
  timestamp: 0
  version: "0.1.0"

nodes:
  - id: "n0"
    label: "R1"
    node_definition: "iosv"
    x: -300
    y: 0
    configuration: ""
    interfaces:
      - id: "i0"
        label: "GigabitEthernet0/0"
        slot: 0
        type: physical
      - id: "i1"
        label: "GigabitEthernet0/1"
        slot: 1
        type: physical
  - id: "n1"
    label: "R2"
    node_definition: "iosv"
    x: 0
    y: -300
    configuration: ""
    interfaces:
      - id: "i0"
        label: "GigabitEthernet0/0"
        slot: 0
        type: physical
      - id: "i1"
        label: "GigabitEthernet0/1"
        slot: 1
        type: physical
  - id: "n2"
    label: "R3"
    node_definition: "iosv"
    x: 300
    y: 0
    configuration: ""
    interfaces:
      - id: "i0"
        label: "GigabitEthernet0/0"
        slot: 0
        type: physical
      - id: "i1"
        label: "GigabitEthernet0/1"
        slot: 1
        type: physical

links:
  - id: "l0"
    n1: "n0"
    i1: "i0"
    n2: "n1"
    i2: "i0"
    label: "l0"
  - id: "l1"
    n1: "n0"
    i1: "i1"
    n2: "n2"
    i2: "i0"
    label: "l1"
  - id: "l2"
    n1: "n1"
    i1: "i1"
    n2: "n2"
    i2: "i1"
    label: "l2"